### ISSUE TITLE
Podcasts

### ISSUE THREAD

**Issue by aareben** [hankhank10/vinylemulator#16]
Hey, is there any chance you could add a podcast feature? When I wake up, I really like to listen to podcasts. the spotify uri is very simple
spotify:show:(podcast ID).
Thanks

**Comment by hankhank10** [comment]
I would have expected this to work. Does it not?

**Comment by ashenshugarRET** [comment]
I was able to play a podcast using an NFC sticker programed with the Spotify URI

**Comment by aareben** [comment]
Oh ok, hadn't tried it yet. Just wondering if it was possible. Thanks for letting me know. Will it just play the most recent one?

**Comment by ashenshugarRET** [comment]
If you have shuffle on it will pick a random one from about the last 10 episodes. If shuffle is off it seems to play the most recent episode, although I haven't tested this extensively.

**Comment by aareben** [comment]
Alright, thanks. Putting on a tag tonight.
