### ISSUE TITLE
Node.js v10.21.0 not supported by NPM

### ISSUE THREAD

**Issue by DJT1423** [hankhank10/vinylemulator#3]
Just trying to setup your project, and I have errored out on the NPM  Node.js install, with the Pi telling me that "npm does not support the current version of Node.js, v.10.21.0".  "Supported releases of Node.js are 4, 6, 7, 8 and 9".

Any suggestions?

**Comment by hankhank10** [comment]
This is a common error but it can usually be safely ignored. Try carrying on with the steps, it should work.

**Comment by DJT1423** [comment]
Solved. Google helped me find out how to install older versions with NVM. I uninstalled v.10 and installed nvm and then node.js v. 8, and now have step 13 successfully implemented. Looking forward to this project.

**Comment by DJT1423** [comment]
Unfortunately, it is now stuck at trying to make the Sonos APi run constantly. When I enter the command: 
pi@raspberrypi:~ $ sudo npm install -g pm2
This is what I get:
npm WARN npm npm does not support Node.js v10.21.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN notice [SECURITY] lodash has the following vulnerability: 1 high. Go here for more details: https://www.npmjs.com/advisories?search=lodash&version=4.17.19 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
/usr/local/bin/pm2 -> /usr/local/lib/node_modules/pm2/bin/pm2
/usr/local/bin/pm2-dev -> /usr/local/lib/node_modules/pm2/bin/pm2-dev
/usr/local/bin/pm2-docker -> /usr/local/lib/node_modules/pm2/bin/pm2-docker
/usr/local/bin/pm2-runtime -> /usr/local/lib/node_modules/pm2/bin/pm2-runtime
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/pm2/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN ws@7.2.5 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.2.5 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.

+ pm2@4.4.0
added 185 packages from 191 contributors in 114.132s

And when I try "pm2 status", I get:
/usr/local/lib/node_modules/pm2/node_modules/chalk/source/index.js:103
	...styles,
	^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/pm2/constants.js:10:14)

When switch the directory and try starting the API:
pi@raspberrypi:~ $ cd node-sonos-http-api
pi@raspberrypi:~/node-sonos-http-api $ pm2 start npm -- start
I get:
/usr/local/lib/node_modules/pm2/node_modules/chalk/source/index.js:103
	...styles,
	^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/pm2/constants.js:10:14)

Any suggestions?

**Comment by DJT1423** [comment]
So aside from getting the api to run constantly, it looks like I should be OK, I get the nice Sonos API page at localhost:5005 and at the Pi IP address elsewhere on my computer. However, when I try to play your track, or albums of my own choosing, I get this error:

http://localhost:5005/music%20room/spotify/now/spotify/spotify:album:2dfTV7CktUEBkZCHiB7VQB

{"status":"error","error":"Got status 500 when invoking /MediaRenderer/AVTransport/Control","stack":"Error: Got status 500 when invoking /MediaRenderer/AVTransport/Control\n    at Object.invoke (/home/pi/node-sonos-http-api/node_modules/sonos-discovery/lib/helpers/soap.js:99:10)\n    at Player.addURIToQueue (/home/pi/node-sonos-http-api/node_modules/sonos-discovery/lib/models/Player.js:616:15)\n    at promise.then (/home/pi/node-sonos-http-api/lib/actions/spotify.js:37:33)\n    at <anonymous>"}

Any thoughts as to what is happening?

**Comment by craigusus** [comment]
Hi @DJT1423 

Your link seems to have too many 'spotify's'. I think it should be like this:
http://localhost:5005/music%20room/spotify/now/spotify:album:2dfTV7CktUEBkZCHiB7VQB
BUT... I have a similar error to yourself. When I get to [Step 5: Play Some Spotify](https://www.hackster.io/mark-hank/sonos-spotify-vinyl-emulator-3be63d#toc-step-5--play-some-spotify-4) and go to the above link the album gets added to my Sonos queue but does not play. I also cannot get it to manually play from the Sonos Windows controller either.
```
{"status":"error","error":"Got status 500 when invoking /MediaRenderer/AVTransport/Control","stack":"Error: Got status 500 when invoking /MediaRenderer/AVTransport/Control\n    at Object.invoke (/home/pi/node-sonos-http-api/node_modules/sonos-discovery/lib/helpers/soap.js:99:10)\n    at Player.trackSeek (/home/pi/node-sonos-http-api/node_modules/sonos-discovery/lib/models/Player.js:552:15)\n    at /home/pi/node-sonos-http-api/lib/actions/spotify.js:38:56\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"}
```

As I have not even got to the stage of installing @hankhank10 's files yet this is probably an issue to take up at https://github.com/jishi/node-sonos-http-api/issues

ALTHOUGH... I was playing with it while writing the above. I rebooted my Sonos Connect Zone Player and now when I go to the link it adds the album to the queue and starts playing it, with no error.

**Comment by DJT1423** [comment]
@craigusus 
Thanks, I think you are correct about the number of "spotify" in the line. I copied it from Step 15 here: https://www.instructables.com/id/Sonos-Spotify-Vinyl-Emulator-SSVE/
However, the correct code "192.168.4.102:5005/Dining Room/spotify/now/spotify:album:2dfTV7CktUEBkZCHiB7VQB" is found at step 5 here: https://www.hackster.io/mark-hank/sonos-spotify-vinyl-emulator-3be63d

Thanks for spotting that. While I am still having difficulty getting the API to auto start, the requested album does play with the code correctly entered.

DJT
