### ISSUE TITLE
NFC Reader Won’t Power On

### ISSUE THREAD

**Issue by ggotnomoney** [hankhank10/vinylemulator#4]
I decided to give this project a try, purchased all the necessary hardware, went through the tutorial step by step with almost no issues at all until I got to the part where I had to plug the NFC reader into the pi. I decided to this on the Raspberry Pi 2 B+ as it was the only pi I had that wasn’t being used. I swapped out psu to one that can handle up to 5v 3.5A and it still didn’t work. I even swapped the pi to a pi 3 I am using on another project and still won’t work. I am out of ideas and am hoping someone can help me out. Thanks for this awesome project, hopefully I can get it to work soon.

**Comment by Esamanoaz** [comment]
Hey, I am [u/Esamanoaz](https://www.reddit.com/u/Esamanoaz) on Reddit who helped you out. This issue has been fixed now on the master branch, so could you close this issue?
