### ISSUE TITLE
Mifare Classic support

### ISSUE THREAD

**Issue by marco79cgn** [hankhank10/vinylemulator#8]
Hi, 

I set up everything without problems but when I tried to read my cards I recognized that Mifare Classic cards are not supported. Why not? I have plenty of them lying around (used for other projects as well). What's the problem with these cards? 

Thx, 
Marco

**Comment by hankhank10** [comment]
The underlying library (nfcpy) only supports NFC Forum Type 1, 2, 3 and 4 Tags. Mifare Classic cards are not supported as these use a proprietary encryption method.

See this answer for more details:

https://stackoverflow.com/questions/49095353/how-to-use-nfcpy-for-mifare-1k-classic
